# Generated by Django 6.0.2 on 2026-03-03 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(help_text='Enter comment about blog here', max_length=500, validators=[django.core.validators.MinLengthValidator(3, 'Too short comment')]),
        ),
    ]
